### ISSUE TITLE
Failed to get DISPLAY: Error: Timed out while waiting for handshake

### ISSUE THREAD

**Issue by liutiming** [ChaosinaCan/vscode-remote-x11#22] opened 2020-07-09 11:09 UTC
Thanks for the great extension! Really hope it could work :) 

System: Ubuntu 20.04 connecting to Ubuntu 18.04 via SSH tunnelling

X11 forwarding works in terminal

in VScode terminal 
echo $DISPLAY
server:25.0

in ubuntu terminal 
echo $DISPLAY
server:17.0

**Comment by liutiming** [comment] 2020-07-09 11:10
On a side note, does it work in Windows?

**Comment by ChaosinaCan** [comment] 2020-07-22 06:06
It works when connecting to Linux from Windows, which is really the only setup I'd been able to test until recently. I'm guessing this is a duplicate of #21

**Comment by liutiming** [comment] 2020-07-26 11:39
hmm at least before the July update the X11 forwarding in windows did not work with powershell's own OpenSSH. I have not tested after the July update

**Comment by ChaosinaCan** [comment] 2020-07-26 20:02
Yeah, that's why I use https://github.com/mscdex/ssh2 instead of the system's SSH to make the connection. I'm going to close this as a duplicate of #21 and use that issue to track issues with Linux-to-Linux connections.

**Closed by ChaosinaCan** 2020-07-26 20:02 UTC
Labels: duplicate
