### ISSUE TITLE
Freezes the terminal

### ISSUE THREAD

**Issue by iuryt** [ChaosinaCan/vscode-remote-x11#30] opened 2020-09-14 01:10 UTC
Hi,

First of all, THANKS very much for this extension.

I am trying to set it up from a Linux to another Linux machine.
If I try to run anything that uses GUI, the terminal freeze and nothing happens, but If I do in a local terminal (not in vs code):
```
ssh -X user@host
eog
```
it works.

The output for `Remote X11 (SSH)` is:
```
Connecting to user@host port 22
Connection ready. Setting up display...
Echo display command is: bash -c "echo DISPLAY=$DISPLAY"
DISPLAY=localhost:12.0
```
And if I go to the terminal and run `echo $DISPLAY` it returns `localhost:12.0`.

**Comment by ChaosinaCan** [comment] 2020-09-14 01:39
This appears to be a duplicate of #21 

I haven't figured out how to get Linux to Linux connections working yet (though I haven't spent much time trying to figure it out recently either). So far it looks like the GUI program is correctly talking to the SSH connection so it thinks it's showing a GUI, but on the local PC the X11 server is rejecting the forwarded connection and not displaying anything.

**Closed** 2020-09-14 01:39 UTC
Labels: duplicate

**Comment by iuryt** [comment] 2020-09-17 16:57
Hi @ChaosinaCan,

I have dual boot and the same happened for my Windows 8 partition.
If I read correctly #21, and you also mentioned that it may be something that happens only for Linux to Linux connections.
One thing I could mention is that it was running well when I tested for the first time on Windows. One day after and it stopped working.

I hope it is somehow useful for solving the problem.
